name: "CI"
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3']
    steps:
      - uses: actions/checkout@v1
      - name: Dump PHP version
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: echo "$PHP_VERSION"
      - run: composer install
      - run: composer test
