name: Static analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ matrix.php }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php }}-
            composer-

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --optimize-autoloader

      - name: Run static analysis
        if: ${{ matrix.analyse }}
        run: vendor/bin/phpstan analyse
